version: '3.9'

services:
  app:
    build: ./
    container_name: app
    environment:
      FLASK_ENV: development
      FLASK_APP: app/main
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_RUN_PORT: "80"
    ports:
      - "${PORT}:80"
    volumes:
      - "${PWD}:/app"
    command: ["flask", "run"]